services:
  apicurio-registry:
    image: apicurio/apicurio-registry:latest
    ports:
      - "8080:8080"
    environment:
      # Use default in-memory storage
      REGISTRY_STORAGE: inmemory
    container_name: apicurio-registry

  apicurio-registry-ui:
    image: apicurio/apicurio-registry-ui:latest
    ports:
      - "8888:8080"
    environment:
      # Point UI to the backend server
      REGISTRY_UI_CONFIG_APIURL: http://apicurio-registry:8080
    depends_on:
      - apicurio-registry
    container_name: apicurio-registry-ui
